### ISSUE TITLE
amtctrl not working after make install

### ISSUE THREAD

**Issue by raulnor516** [sdague/amt#23]
Tonight I cloned your repo to my raspberry pi zero running the latest Raspbian Lite. I ran "sudo make install", which ran with no errors. When I attempted to call amtctrl, I received the following error message:

Traceback (most recent call last):
  File "/usr/local/bin/amtctrl", line 7, in <module>
    import requests
ImportError: No module named requests

I don't know enough about python or Make to understand what's wrong here, I'm pretty new to all this.

**Comment by raulnor516** [comment]
Actually, I was wrong. While running Make, I did receive the following errors, but the Make process continued:

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)

**Comment by sdague** [comment]
What version of python is on that environment?

**Comment by raulnor516** [comment]
Looks like raspbian defaults to 2.7.13. Will I need to install 3 and re-Make the program?

**Comment by sdague** [comment]
You shouldn't, the only thing I can imagine is that it doesn't actually have setuptools, which is going to make the install process not handle the requirements correctly.

**Comment by sdague** [comment]
apt-get install python-setuptools first, then try make install again.

**Comment by raulnor516** [comment]
So I installed python-setuptools and ran make install, and now I've got a new set of fun errors :)

Traceback (most recent call last):
  File "/usr/local/bin/amtctrl", line 4, in <module>
    __import__('pkg_resources').run_script('amt==0.8.0', 'amtctrl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1486, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'amtctrl'

The make seemed to work fine, the only errors that showed were some errors similar to these:

warning: no previously-included files matching '*.pyc' found under directory 'tools'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
warning: no files found matching 'requirements.txt'

**Comment by raulnor516** [comment]
Figured it out myself. Neither "make install" or "easy_install" worked properly, they both returned errors, but downloading and using pip (from https://pip.pypa.io/en/stable/installing/) and using "pip install" made everything finally work properly.
